---
- name: BIG-IP SETUP
  hosts: webapp
  connection: local
  gather_facts: false
  vars:
    provider:
      server: "{{private_ip}}"
      user: "{{ansible_user}}"
      password: "{{ansible_ssh_pass}}"
      server_port: 8443
      validate_certs: false

  tasks:

  - name: CREATE NODES
    bigip_node:
      provider: "{{ provider }}"
      host: "{{hostvars[item].ansible_host}}"
      name: "{{hostvars[item].inventory_hostname}}"
    loop: "{{ groups['web'] }}"

