---
- name: Create Application HTTPS
    hosts: bigip
    gather_facts: false
    connection: local

    vars:
        virual_server_name: """
        server_port: 80
        snat: auto
        persistance: cookie
        app_locations:
        - datacenter_name: aws
            vip_address: 10.1.1.14
            pool_members:
            - 10.1.1.229
            - 10.1.1.149
            - 10.1.1.150
            pool_monitor: http
            pool_servicePort: 80

    tasks:
    - name: ADD VIRTUAL SERVER
        bigip_virtual_server:
        provider:
            server: "{{private_ip}}"
            user: "{{ansible_user}}"
            password: "{{ansible_ssh_pass}}"
            server_port: 8443
            validate_certs: no
        name: "vip"
        destination: "{{private_ip}}"
        port: "443"
        enabled_vlans: "all"
        all_profiles: ['http','clientssl','oneconnect']
        pool: "http_pool"
        snat: "Automap"


app_name: App1
tenant: Tenant1
app_template: http
server_port: 80
snat: self
persistance: cookie
app_locations:
  - datacenter_name: aws
    vip_address: 10.1.1.14
    pool_members:
      - 10.1.1.229
      - 10.1.1.149
      - 10.1.1.150
    pool_monitor: http
    pool_servicePort: 80